name: dreamweaver
description: "DreamWeaver is a stunning Flutter app designed to capture, analyze, and enrich your dream experiences, featuring seamless Firebase integration and a captivating dark theme."
publish_to: "none"
version: 1.0.0

environment:
  sdk: ^3.6.0

dependencies:
  url_launcher: ^6.0.0
  purchases_flutter: ^9.0.0
  fl_chart: 0.68.0
  share_plus: ^12.0.0
  video_player: '>=2.9.2'
  path_provider: ^2.0.0
  flutter_tts: ^4.0.0
  google_sign_in: '>=6.2.1'
  firebase_crashlytics: ^5.0.0
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.8
  google_fonts: ^6.1.0
  provider: ^6.1.2
  go_router: ^16.2.0
  firebase_core: ^4.3.0
  cloud_firestore: '>=5.5.0'
  firebase_auth: '>=5.3.3'
  firebase_storage: ^13.0.0
  cloud_functions: ^6.0.0
  firebase_analytics: ^12.0.0
  firebase_messaging: ^16.0.0
  http: ^1.0.0
  flutter_sound: ^9.0.0
  speech_to_text: ^7.0.0
  permission_handler: ^12.0.0
  shared_preferences: ^2.0.0
  intl: 0.20.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true

flutter_launcher_icons:
  android: true
  ios: true
  image_path: assets/icons/dreamflow_icon.jpg
  remove_alpha_ios: true
